model:
  name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  torch_dtype: "bfloat16"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"

sft:
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  optim: "adamw_torch"
  learning_rate: 0.0001
  lr_scheduler_type: "cosine"
  num_train_epochs: 1
  logging_steps: 100
  fp16: true
  gradient_checkpointing: true
  save_steps: 1000
  eval_steps: 1000
  save_strategy: "steps"
  eval_strategy: "steps"
  max_steps: 10000
  dataset_text_field: "text"
  packing: false